[package]
name = "robot9000"
version = "0.1.0"
authors = ["Galen G <git@galenguyer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
sqlite = "0.25.0"
lazy_static = "1.4.0"
